version: "3"

services:
  attacker:
    image: handsonsecurity/seed-ubuntu:large
    container_name: attacker
    hostname: attacker
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes:/volumes
    network_mode: host

  server:
    image: handsonsecurity/seed-ubuntu:large
    container_name: server
    hostname: server
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes:/volumes
    sysctls:
      - net.ipv4.tcp_syncookies=0
      - net.ipv4.tcp_max_syn_backlog=64
      - net.ipv4.tcp_synack_retries=100
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.5
    command: bash -c "echo 'Some secret data' > /home/seed/secret.txt &&
      /etc/init.d/openbsd-inetd start  &&
      tail -f /dev/null"

  user1:
    image: handsonsecurity/seed-ubuntu:large
    container_name: user1
    hostname: user1
    tty: true
    cap_add:
      - ALL
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.6

    command: bash -c "
      /etc/init.d/openbsd-inetd start  &&
      tail -f /dev/null"

  user2:
    image: handsonsecurity/seed-ubuntu:large
    container_name: user2
    hostname: user2
    tty: true
    cap_add:
      - ALL
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.7

    command: bash -c "
      /etc/init.d/openbsd-inetd start  &&
      tail -f /dev/null"

  firefox:
    image: jlesage/firefox
    container_name: firefox
    hostname: firefox
    restart: always
    ports:
      - "5800:5800"
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.10

networks:
  net-10.9.0.0:
    name: net-10.9.0.0
    ipam:
      config:
        - subnet: 10.9.0.0/24
